export const SOCKET_EVENTS = {
    USER_TYPING: "user_typing",
    USER_STOPPED_TYPING: "user_stopped_typing",

    USER_STATUS_CHANGED: "user_status_changed",

    NEW_MESSAGE: "new_message",
    NEW_MESSAGE_FILE: "new_message_file",
    NEW_MESSAGE_MEDIA: "new_message_media",
    NEW_MESSAGE_VOICE: "new_message_voice",
    NEW_MESSAGE_LINK: "new_message_linkPreview",
    NEW_MESSAGE_CALL: "new_message_call",
    MESSAGE_EDITED: "message_edited",
    MESSAGE_DELETED: "message_deleted",
    MESSAGE_REACTED: "message_reacted",
    MESSAGE_FORWARDED: "message_forwarded",
    MESSAGE_SEEN: "message_seen",
    MESSAGE_PINNED: "message_pinned",
    MESSAGE_UNPINNED: "message_unpinned",
    MESSAGE_MENTION: "mention_received",
    MESSAGE_SYSTEM_ROOM: "message_system_room",

    GROUP_UPDATED: "conversation_updated",
    GROUP_CREATED: "group_created",
    GROUP_MEMBER_ADDED: "group_member_added",
    GROUP_ADDED: "group_added",
    GROUP_MEMBER_REMOVED: "group_member_removed",
    GROUP_REMOVED: "group_removed",
    GROUP_MEMBER_LEFT: "group_member_left",
    GROUP_LEFT_SELF: "group_left_self",
    GROUP_ROLE_CHANGED: "group_role_changed",
    GROUP_DISSOLVED: "group_dissolved",
    GROUP_JOIN_REQUESTED: "group_join_requested",
    GROUP_REQUEST_HANDLED: "group_request_handled",
    GROUP_REQUEST_ADDED: "group_request_added",
    GROUP_REQUEST_REJECTED: "group_request_rejected",

    FRIEND_REQUEST_RECEIVED: "friend_request_received",
    FRIEND_REQUEST_ACCEPTED: "friend_request_accepted",
    FRIEND_REQUEST_REJECTED: "friend_request_rejected",

    CALL_INITIATED: "call_initiated",
    CALL_STARTED: "call_started",
    CALL_BUSY: "call_busy",
    CALL_ACCEPTED: "call_accepted",
    CALL_REJECTED: "call_rejected",
    CALL_ENDED: "call_ended",
    CALL_CANCELLED: "call_cancelled",

    CALL_OFFER: "call_offer",
    CALL_ANSWER: "call_answer",
    CALL_ICE_CANDIDATE: "call_ice_candidate",

    GROUP_CALL_STARTED: "group_call_started",
    GROUP_CALL_JOINED: "group_call_joined",
    GROUP_CALL_LEFT: "group_call_left",
    GROUP_CALL_ENDED: "group_call_ended",
    GROUP_CALL_PARTICIPANTS: "group_call_participants",
    GROUP_CALL_REDIRECT: "group_call_redirect"
} as const;